apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-admin
spec:
  selector:
    matchLabels:
      app: admin
  replicas: 1
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: broker-admin
          image: 757833611845.dkr.ecr.ap-northeast-1.amazonaws.com/dev-broker-admin:akano-demo
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
          ports:
            - containerPort: 8090
