apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: broker-api
          image: 757833611845.dkr.ecr.ap-northeast-1.amazonaws.com/dev-broker-api:akano-demo
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
          ports:
            - containerPort: 8080
